### PR TITLE
Fixes for numerous niggles

### PR DESCRIPTION
**Pull request by Synchro**
It would be really nice to apply some kind of coding standard; it's all horribly inconsistent. Meanwhile, here are some fixes for some small copy changes, and a bit of reformatting. You can cherry pick them if you like.

### CODE REVIEW

**Comment by PeterMosmans** [comment]
Hey @Synchro - thank you so much for all the additions, much appreciated. Usually I prefer atomic commits / pull requests, but this looks perfect.
For next time: Would you mind using the conventional commits standard (see https://www.conventionalcommits.org/en/v1.0.0/ ) for commit messages? The `CHANGELOG.md` is generated automagically from all commit messages, _if_ they adhere to that standard. e.g., for this time it could be `style: ` changes, as this commit doesn't change the framework itself.

Thanks!

**Comment by PeterMosmans** [comment]
Ah - I wanted to merge all changes, but I see you've added a framework change https://github.com/radicallyopensecurity/pentext/pull/140/commits/83325f0ff98af2d28ed295a8fb9bff9cab771ea1
Would you mind removing that one from the PR and generate a separate one for that? Thanks!

**Comment by Synchro** [comment]
OK, I removed those 2 commits, second PR incoming

**Comment by Synchro** [comment]
All done, after a bit of force-pushing...

**Pull request merged**
