### PR TITLE
Import a Makefile for the sample report

### PR DESCRIPTION
**Pull request by khorben**
Hi! I have written a Makefile to help with the generation of reports with pentext.

Before merging this pull-request, I think I found a bug, as per the output below:
```
$ (cd xml && make)
[...]
mkdir -p -- target
java -jar ../saxon9he.jar \
     -s:"sample-report/source/report.xml" \
     -xsl:"xslt/generate_report.xsl" \
     -o:"target/report_sample-report.fo" \
     -xi
Type error in xsl:when/@test on line 41 column 52 of numbering.xslt:
  XPTY0004: Cannot compare xs:string to xs:boolean
  at xsl:apply-templates (file:/home/khorben/Projects/ROS/pentext/xml/xslt/fo_inline.xslt#136)
     processing /pentest_report/section[2]
  at xsl:apply-templates (file:/home/khorben/Projects/ROS/pentext/xml/xslt/block.xslt#50)
     processing /pentest_report/section[5]/section[1]/finding[12]/description[1]/p[1]/a[1]
  at xsl:apply-templates (file:/home/khorben/Projects/ROS/pentext/xml/xslt/findings.xslt#101)
     processing /pentest_report/section[5]/section[1]/finding[12]/description[1]/p[1]
  at xsl:apply-templates (file:/home/khorben/Projects/ROS/pentext/xml/xslt/functions_params_vars.xslt#458)
     processing /pentest_report/section[5]/section[1]/finding[12]/description[1]
  in  
  in  
  at xsl:apply-templates (file:/home/khorben/Projects/ROS/pentext/xml/xslt/structure.xslt#29)
     processing /pentest_report/section[1]/section[6]/generate_findings[1]
  at xsl:apply-templates (file:/home/khorben/Projects/ROS/pentext/xml/xslt/structure.xslt#29)
     processing /pentest_report/section[1]/section[6]
  at xsl:apply-templates (file:/home/khorben/Projects/ROS/pentext/xml/xslt/pages.xslt#191)
     processing /pentest_report/section[1]
  at xsl:call-template name="generate_pages" (file:/home/khorben/Projects/ROS/pentext/xml/xslt/pages.xslt#176)
  at xsl:call-template name="Content" (file:/home/khorben/Projects/ROS/pentext/xml/xslt/generate_report.xsl#56)
Cannot compare xs:string to xs:boolean
Makefile:20: recipe for target 'target/report_sample-report.fo' failed
make: *** [target/report_sample-report.fo] Error 2
```

This should probably be fixed first.

About the Makefile itself, I will welcome suggestions as to how to better integrate it with the project, if necessary.

### CODE REVIEW

**Comment by skyanth** [comment]
Hey Pierre, I think that error is a consequence of your xml not being valid (most likely the treat level of one or more findings in your sample report not corresponding to one of the allowed values). Can you check?

**Comment by khorben** [comment]
Well, the XML is not from me, it is from the repository itself (in `sample-report/source/report.xml`).

**Comment by skyanth** [comment]
Well that has me completely stumped. You can work around it by commenting out the reference to the spearphishing finding in line 420:
```
<xi:include xmlns:xi="http://www.w3.org/2001/XInclude"
                                href="findings/spearphishing.xml"/>```
But I can't for the life of me see why this finding in particular is giving problems right now. I'll look into it.

**Comment by skyanth** [comment]
Took me some hard staring but it's fixed now, pull and retry?

**Comment by khorben** [comment]
> Took me some hard staring but it's fixed now, pull and retry?

Yes, the report generates as expected now.

**Pull request merged**
